### ISSUE TITLE
multi-span results

### ISSUE THREAD

**Issue by Lomarandil** [buddyd16/theToolbox#6]
I think you might literally be implementing this as I write, or I just didn't notice the feature earlier.

But the multi-span calculation is obviously not fully implemented yet.

![image](https://user-images.githubusercontent.com/45415987/167245998-d683e41d-bed6-45bf-9f8b-b281702ae8e7.png)
(distributed load but linear moment diagram)

**Comment by buddyd16** [comment]
@Lomarandil can you let me know what your inputs were for this one? 

I don't get similar behavior with a similar test case but my load values are lower based on the moment results:
![image](https://user-images.githubusercontent.com/12416202/167251660-147895b1-1a72-4db8-a320-c520a8ecba99.png)

**Comment by buddyd16** [comment]
It may be that the point load you added was significantly larger than the distributed load which would make it dominate the results see below where the curve appears straight due to the magnitude of the moment created by the point load:
![image](https://user-images.githubusercontent.com/12416202/167251831-ef6da091-176d-4780-9a61-5d7546afe7fe.png)

However the load functions do contain the higher order terms coming from the distributed load:
(they are however dwarfed by the linear terms)
![image](https://user-images.githubusercontent.com/12416202/167251885-dbb468cc-eaf7-47ac-9c6d-1491acffc3dd.png)

**Comment by Lomarandil** [comment]
Oh, false alarm. This is a side effect of that other bug that toggles the
input back to imperial units unexpectedly. So instead of loads of 5-8kPa
and a small point load of 20kN, I was applying loads of 5-8psf and a
relatively larger point load of 20kips. So the moment diagram is correctly
mostly linear.
